//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int IterationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int AreaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Iteration Iteration { get; set; }
        public virtual Status Status { get; set; }
    }
}
